services:
  api:
    build:
      dockerfile: Dockerfile
      target: prod
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - horahora

  db:
    image: mongo
    ports:
      - "27017"
    volumes:
      - db:/data/db
    networks:
      - horahora

volumes:
  db:

networks:
  horahora:
    driver: bridge
