name: automatons
version: 0.1.0-dev.1
publish_to: none

environment: { sdk: ">=3.0.0 <4.0.0" }
dependencies:
  {
    dart_frog: ^1.0.0,
    dart_frog_auth: ^1.0.0,
    equatable: ^2.0.5,
    mongo_dart: ^0.9.1,
    json_annotation: ^4.8.1,
  }
dev_dependencies:
  {
    build_runner: ^2.4.6,
    json_serializable: ^6.7.1,
    lint: ^2.0.20,
    mocktail: ^0.3.0,
    test: ^1.19.2,
  }
