name: automatons
version: 0.1.0-dev.1
publish_to: none

environment: { sdk: ">=3.0.0 <4.0.0" }
dependencies:
  {
    dart_frog: ^1.0.0,
    dart_frog_auth: ^1.0.0,
    equatable: ^2.0.5,
    mongo_dart: ^0.9.1,
  }
dev_dependencies: { lint: ^2.0.20, mocktail: ^0.3.0, test: ^1.19.2 }
