name: horahora
version: 0.1.0-dev.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  crypto: ^3.0.3
  csv: ^5.0.2
  dart_frog: ^1.0.0
  dart_frog_auth: ^1.0.0
  dart_jsonwebtoken: ^2.14.0
  deep_pick: ^1.0.0
  dotenv: ^4.1.0
  equatable: ^2.0.5
  mongo_dart: ^0.9.1
  uuid: ^3.0.7

dev_dependencies:
  lint: ^2.0.20
  mocktail: ^0.3.0
  test: ^1.19.2
