version: "3"

services:
  server:
    build:
      context: ../../
      dockerfile: ./pkgs/hours/Dockerfile
      target: prod
    image: yourilieverdink/automata-hours:${TAG:-latest}
    ports:
      - "8000:8080"
